openapi: 3.0.0
info:
  title: User Management API (Generated Spec)
  version: 1.0.0
  description: API for managing user resources based on the provided userRepository.
servers:
  - url: /api
    description: User API Base Path

paths:
  /user:
    get:
      summary: 獲取使用者列表
      operationId: getUsers
      tags:
        - User
      responses:
        '200':
          description: 成功獲取使用者列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
    
    post:
      summary: 新增使用者
      operationId: addUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: 成功創建使用者
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      summary: 更新使用者
      operationId: updateUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 成功更新使用者
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    
    delete:
      summary: 刪除使用者
      operationId: deleteUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIdRequest'
      responses:
        '200':
          description: 刪除成功，返回空或成功訊息
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
      required:
        - id
        - name
        - age

    NewUser:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      required:
        - name
        - age

    UserIdRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
      required:
        - id

    UserListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - data