/* tslint:disable */
/* eslint-disable */
/**
 * User Management API (Generated Spec)
 * API for managing user resources based on the provided userRepository.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeleteUser200Response {
    'success'?: boolean;
}

